sonar.projectKey=vod-streaming-platform-upload
sonar.projectName=VOD Streaming Platform Upload
sonar.organization=michelalmeidasilva
sonar.sources=.
sonar.exclusions=node_modules/**,dist/**,coverage/**,.next/**,.scannerwork/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
